package main

import "strconv"
import "os"
import "fmt"
import "time"
//import "sync"

// Generate some numbers. (As it happens, the ones from 0..n.)
func generator(n int) func(func(int) bool) {
  return func(yield func(int) bool) {
    for i := 0; i < n; i++ {
      yield(i)
    }
  }
}

// Sum up the numbers generated by `generator`.
func sum(g func(func(int) bool)) int {
  result := 0
  for v := range g {
    result += v
  }
  return result
}

func main() {
  first, err := strconv.Atoi(os.Args[1])
  if err != nil { panic("arg not parsed as int") }
  last, err := strconv.Atoi(os.Args[2])
  if err != nil { panic("arg not parsed as int") }
  
  for i := first; i <= last; i++ {
    start := time.Now()
		n := i * 1000000
    fmt.Println(sum(generator(n)))
    fmt.Println(i)
    fmt.Println("Time: ", time.Since(start));
  }
}
